### PR TITLE
Ritam

### PR DESCRIPTION
**Pull request by Shahrukh-Chishti**
there are too many histogram...wouldn't look nice...is its possible to develop a gif out of them too ??
and is this all ??

### CODE REVIEW

**Comment by Shahrukh-Chishti** [comment]
feel free to argue for and against..
also provide some description about these images

**Comment by ritams** [comment]
Ok  i will make some gif of the histogram

**Comment by Shahrukh-Chishti** [comment]
you would have to commit these changes to your branch.

**Comment by ritams** [comment]
Okey

**Pull request merged**
